# Generated by Django 2.2.6 on 2020-03-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200323_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='oerder_plcae',
            new_name='order_place',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
